### ISSUE TITLE
[iOS] System.Reflection.Emit is not supported

### ISSUE THREAD

**Issue by zhangzhibin** [bitcraftCoLtd/protobuf3-for-unity#4]
I got this exception when running on iOS when trying to print out a protobuf message using:

```
        AddressBook book = new AddressBook ();
        Person person = new Person
        {
            Id = 1,
            Name = "Foo",
            Email = "foo@bar",
            Phones = { new Person.Types.PhoneNumber { Number = "555-1212" } }
        };
        book.People.Add (person);
        person.Id = 2;
        book.People.Add (person);

        Debug.LogFormat ("Address Book:\n{0}", book);  // <=== Exception here
```

Here is the output in XCode:

> Unhandled Exception: System.NotSupportedException: /Users/builduser/buildslave/unity/build/Tools/il2cpp/il2cpp/libil2cpp/icalls/mscorlib/System.Reflection.Emit/DynamicMethod.cpp(26) : Unsupported internal call for IL2CPP:DynamicMethod::destroy_dynamic_method - System.Reflection.Emit is not supported.
>   at System.Reflection.Emit.DynamicMethod.Finalize () [0x00000] in <filename unknown>:0 
> UnityEngine.UnhandledExceptionHandler:PrintException(String, Exception)
> UnityEngine.UnhandledExceptionHandler:HandleUnhandledException(Object, UnhandledExceptionEventArgs)
> 
> (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

I did some experiment and found it was caused by those methods in Google.Protobuf.Reflection.ReflectionUtil.

They uses System.Linq.Expressions to generate code at runtime which is not allowed in iOS.

I tried to replace those Linq.Expressions usages and was able to make them work. You may find the changes in my fork:

> https://github.com/zhangzhibin/protobuf3-for-unity-ex/blob/v3.0.0/src/Google.Protobuf/Reflection/ReflectionUtil.cs

I don't have very much experience in C#, so please let me know if you find any risk in my changes.

Thanks

**Comment by qbrandon** [comment]
Your commit seems to be just fine.
Since this is Google code, could you please submit a PR there: https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/Reflection/ReflectionUtil.cs

We could apply the change locally, but it would be better to patch upstream because:
- we want to avoid diverging from the Google repo
- if there is a reason why the code was written as it is, we want to know about it

**Comment by zhangzhibin** [comment]
@qbrandon Sorry for late response and thanks for your feedback. I just commented on the google protobuf thread.

**Comment by qbrandon** [comment]
FYI, we will soon need to get this running on iOS w/ IL2CPP as well, so this is a matter that is of great interest to us as well.
As you could see from the discussion on the Google repo, this is not a trivial change, and it appears unlikely to land there.
What will likely happen is that we look for ways to mitigate or isolate the performance cost of this fix, and depending on the result, either propose to merge it in the Google repo or apply it locally here.
Please wait a bit until we get this figured out.

**Comment by qbrandon** [comment]
Ok, so after weighing in on our options, we decided to just go ahead and integrate your changes to the repo.
The latest release includes those changes so please let us know if this works for you so we may close this issue.

For those interested in the reflection behind this the bottom line here is:
- the performance cost should not show a visible impact on most Unity applications (client-side network)
- there are little chance to see this modification land in the Google repo as-is
- we can always drop .NET Standard 1.0 support and test alternative ways to fix this, but it has to be worth the time and effort

And finally here is a link to the discussion with the Google repo collaborators and participants:
https://github.com/google/protobuf/issues/644

**Comment by zhangzhibin** [comment]
Yes, I am happy to see a workable version of Protobuf 3 for Unity. Thanks for your effort.
