### ISSUE TITLE
What's this project theory?

### ISSUE THREAD

**Issue by molixiaoge** [bitcraftCoLtd/protobuf3-for-unity#5]
Sorry,i am new to c#. 
I compare the google orgin source with yours,and the only change is project.json.
I know the source code use c# 6.0,which unity can not use it.
If i want to use it within unity,the  only thing i can do, is build the source with .net core 3.5 and copy the dll within the unity project?
I know the unity use .net 2.0,but does unity can use the dll with .net 3.5?
Finally,sorry for my poor english.

Look forward to your reply.

**Comment by TanukiSharp** [comment]
The language and the runtime are two different things.

If you build the code with a C# 6.0 compiler, it can totally produce a binary compatible with an older runtime, such as .NET 3.5.

So yes, you have to build the code, say with Visual Studio 2015 Community edition (we provide prebuilt .dll files for convenience, right here: https://github.com/bitcraftCoLtd/protobuf3-for-unity/releases)

Unity uses an implementation of the .NET 2.0 runtime, which didn't change until .NET 4.0, so it supports assemblies up to 3.5, no problem about that.

I hope I could answer all your questions and it helped.

**Comment by molixiaoge** [comment]
Oh,i See,Thanks for your reply!

**Comment by dtandersen** [comment]
Thanks for porting it over to Unity.
