### ISSUE TITLE
Support C# 6.0 and protoc v3.6.0

### ISSUE THREAD

**Issue by nntoanbkit** [bitcraftCoLtd/protobuf3-for-unity#8]
Would you please update the assembly so it can work with dotnet 4.6 (or higher) and newer version of `protoc`.

The [lastest version](https://github.com/bitcraftCoLtd/protobuf3-for-unity/releases/tag/v3.0.0_ga_noJIT) does not work with `protoc` with version higher than 3.4.1 (see #7 ).

I can send a PR, please let me know where to start. Thanks.

**Comment by TanukiSharp** [comment]
Hello Jubei,

We started this fork for a very specific project that requires the very specific 3.0.0 version of Protobuf running on C# 4.0 / .NET Framework 3.5 runtime version of Unity.

May I recommend you to use the official Protobuf repository from Google ? I think now they support older and newer versions of Unity.

**Comment by nntoanbkit** [comment]
Thanks for your response.

The assembly still works with C# 6.0 when I try to change the `Scripting Runtime Version` in Unity to `.Net 4x Equivalent` (access from `Edit > Project Settings > Player`). Sorry my bad for not testing that first.

And the sources file generated by `protoc` 3.4.1 seems to work with files generated by higher version without any problems.

**Comment by TanukiSharp** [comment]
Thanks for reporting.

Great to hear you could fix your problem, and this information might be valuable in case we upgrade someday.

Thanks a lot.
